#!/usr/bin/env python3
"""Curate atomic clauses/practices from OCRed reference reports."""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REFERENCE_LIBRARY_ROOT = Path(
    os.environ.get("HERITAGE_REFERENCE_LIBRARY", "/Users/drevan01/Desktop/文物影响评估与保护方案资料库")
)
LIB_ROOT = REFERENCE_LIBRARY_ROOT / "01_法规政策与标准/法规条文库"
SCAN_ROOT = LIB_ROOT.parent / "环境与施工标准资料库" / "reference_report_scan"

SOURCE_OUT = LIB_ROOT / "reference_report_sources.jsonl"
CLAUSE_OUT = LIB_ROOT / "reference_report_atomic_clauses.jsonl"
MANIFEST_OUT = LIB_ROOT / "reference_report_atomic_manifest.json"


def now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def source(source_id: str, title: str, filename: str, note: str) -> dict[str, Any]:
    text_path = SCAN_ROOT / filename
    return {
        "source_id": source_id,
        "source_title": title,
        "source_type": "reference_report",
        "source_code": "",
        "source_version": "",
        "source_status": "reference_only",
        "local_path": str(text_path),
        "text_path": str(text_path),
        "source_note": note,
        "text_chars": text_path.stat().st_size if text_path.exists() else 0,
        "generated_at": now_iso(),
    }


SOURCES = [
    source(
        "REF_S26_PROTECTION_PLAN",
        "S26纳日松至兰家梁段高速公路项目文物保护方案 OCR",
        "高速公路保护方案.txt",
        "参考报告 OCR 文本；用于提取既有文评/保护方案中的减缓措施做法，不作为正式法规原文。",
    ),
    source(
        "REF_S26_IMPACT_ASSESSMENT",
        "S26纳日松至兰家梁段高速公路项目文物影响评估报告 OCR",
        "高速公路影响评估报告.txt",
        "参考报告 OCR 文本；用于提取既有文评中的影响分析、方案比选和减缓措施做法。",
    ),
    source(
        "REF_CHIFENG_HSR_GREAT_WALL",
        "新建赤峰至京沈高铁喀左站铁路工程穿越燕北长城文物影响评估报告 OCR",
        "新建赤峰至京沈高铁喀左站铁路工程穿越燕北长城文物影响评估报告.txt",
        "参考报告 OCR 文本；用于提取铁路隧道下穿长城场景中的振动控制和保护措施做法。",
    ),
    source(
        "REF_AMO_RAILWAY",
        "内蒙古呼伦贝尔市新建阿荣旗至莫旗铁路文物影响评估报告 OCR",
        "内蒙古呼伦贝尔市新建阿荣旗至莫旗铁路文物影响评估报告.txt",
        "参考报告 OCR 文本；用于提取铁路建设涉及环境标准和施工保护做法。",
    ),
]


def clause(
    clause_id: str,
    source_id: str,
    source_title: str,
    location: str,
    text: str,
    control_object: str,
    applies_to: str,
    impact_factors: list[str],
    trigger_keywords: list[str],
    project_types: list[str] | None = None,
    heritage_types: list[str] | None = None,
    control_value: str = "",
    related_standard: str = "",
) -> dict[str, Any]:
    source_row = next(item for item in SOURCES if item["source_id"] == source_id)
    return {
        "clause_id": clause_id,
        "source_id": source_id,
        "source_title": source_title,
        "source_type": "reference_report_practice",
        "source_code": "",
        "source_version": "",
        "source_status": "reference_only",
        "granularity": "atomic_practice",
        "clause_location": location,
        "clause_text": text,
        "control_object": control_object,
        "control_value": control_value,
        "control_unit": "",
        "applies_to": applies_to,
        "zones": [],
        "topics": [],
        "trigger_keywords": trigger_keywords,
        "project_types": project_types or [],
        "heritage_types": heritage_types or ["great_wall"],
        "impact_factors": impact_factors,
        "local_path": source_row["local_path"],
        "text_path": source_row["text_path"],
        "source_url": "",
        "notes": (
            "参考报告做法原子条目；用于提示同类项目可调用的规范或减缓措施，"
            "不是正式法规标准原文。"
            + (f" 关联规范：{related_standard}。" if related_standard else "")
        ),
    }


CLAUSES = [
    clause(
        "REF-S26-PLAN-SPOIL-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.6 禁设取弃土场，OCR 行1371-1377",
        "涉及长城保护范围或新发现长城遗址保护范围时，应禁止在该区域内设置取土场、弃土场，以保留原有历史环境风貌。",
        "取弃土场设置",
        "公路、桥梁等线性工程穿越或邻近长城保护范围、新发现长城遗址保护范围的场景",
        ["取弃土", "地形地貌", "历史风貌", "水土保持"],
        ["取土场", "弃土场", "历史环境风貌", "保护范围"],
        ["road", "bridge"],
    ),
    clause(
        "REF-S26-PLAN-NOISE-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.7 噪声防治措施，OCR 行1378-1382",
        "施工噪声接近文物遗址或居民生活环境时，应加强施工单位管理，选择合适施工方法和施工时段，避免机械施工噪声造成破坏或扰民。",
        "施工噪声",
        "施工噪声影响文物遗址周边环境或居民生活环境的场景",
        ["噪声", "施工期", "场界噪声"],
        ["施工噪声", "施工时段", "机械施工", "文明施工"],
        ["road", "bridge"],
        related_standard="建筑施工噪声排放标准、声环境相关导则",
    ),
    clause(
        "REF-S26-PLAN-VIB-MONITOR-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.1 工程振动监测方法，OCR 行1386-1395",
        "施工振动可能影响文物遗址时，应监测振动最大速度值和主频率，并分析施工参数与地面振动效应之间的关系。",
        "施工振动监测指标",
        "施工振源接近文物遗址或可能经地基传播影响文物本体的场景",
        ["振动", "施工期", "监测"],
        ["振动监测", "最大速度值", "主频率", "施工参数"],
        ["road", "bridge", "railway"],
        related_standard="古建筑防工业振动技术规范",
    ),
    clause(
        "REF-S26-PLAN-VIB-MONITOR-002",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.2 振动监测方案，OCR 行1396-1402",
        "布置振动监测点时，应根据振动源与监测对象的位置关系设置测点，至少包括距振动源最近位置和监测对象离振源较远位置，并保证测点数量足以分析传播关系。",
        "振动监测点布设",
        "需要开展施工振动现场监测的文物影响评估或保护方案",
        ["振动", "监测", "施工期"],
        ["测点布置", "振动源", "监测对象", "100米"],
        ["road", "bridge", "railway"],
    ),
    clause(
        "REF-S26-PLAN-VIB-MONITOR-003",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.3-5.8.4 监测数据处理与结果分析，OCR 行1422-1428",
        "振动监测数据应进行波形分析、频率分析和矢量处理，并结合相关标准评价监测结果，提出施工参数调整建议。",
        "振动监测数据处理",
        "施工振动监测已取得实测数据后的分析评价环节",
        ["振动", "监测", "数据分析"],
        ["波形分析", "频率分析", "矢量处理", "施工参数"],
        ["road", "bridge", "railway"],
    ),
    clause(
        "REF-S26-PLAN-VIB-TRENCH-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.5 减振措施，OCR 行1429-1438",
        "桥墩基础等施工振源接近长城遗址时，可在距振源一定距离处设置填充式减振沟，以削减振源向外传播的能量。",
        "减振沟",
        "桥墩基础施工、道路桥梁施工或其他近距离施工振源影响长城遗址的场景",
        ["振动", "减振", "施工期"],
        ["减振沟", "填充式", "桥墩基础", "振源"],
        ["road", "bridge"],
        control_value="底宽1m、深2m（参考报告做法）",
    ),
    clause(
        "REF-S26-PLAN-VIB-ROAD-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.5 减振措施，OCR 行1439-1445",
        "公路工程振源减振可通过加强养护维修、提高路面平整度、保持道路良好技术状况来降低车辆振动影响。",
        "路面平整度与养护",
        "公路运营振动可能影响长城遗址或周边结构物的场景",
        ["振动", "运营期", "减振"],
        ["路面平整度", "养护维修", "运营振动"],
        ["road"],
        related_standard="古建筑防工业振动技术规范（GB/T 50452-2008）",
    ),
    clause(
        "REF-S26-PLAN-VIB-ROAD-002",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.5 减振措施，OCR 行1439-1445",
        "公路工程振源减振可采用沥青混凝土路面，以降低车辆通行引起的振动影响。",
        "路面结构减振",
        "公路运营振动可能影响长城遗址或周边结构物的场景",
        ["振动", "运营期", "减振"],
        ["沥青混凝土路面", "运营振动"],
        ["road"],
        related_standard="古建筑防工业振动技术规范（GB/T 50452-2008）",
    ),
    clause(
        "REF-S26-PLAN-VIB-ROAD-003",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.5 减振措施，OCR 行1439-1445",
        "公路工程振源减振可通过限制行车速度来降低车辆通行振动。",
        "车辆限速减振",
        "公路运营振动可能影响长城遗址或周边结构物的场景",
        ["振动", "运营期", "交通管控"],
        ["限制行车速度", "限速", "运营振动"],
        ["road"],
        related_standard="古建筑防工业振动技术规范（GB/T 50452-2008）",
    ),
    clause(
        "REF-S26-PLAN-VIB-ROAD-004",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.8.5 减振措施，OCR 行1439-1445",
        "公路桥梁工程可采用减振型桥梁伸缩缝，以降低车辆通过桥梁时产生的振动影响。",
        "桥梁伸缩缝减振",
        "桥梁运营振动可能影响长城遗址或周边结构物的场景",
        ["振动", "运营期", "减振"],
        ["减振型桥梁伸缩缝", "桥梁", "运营振动"],
        ["road", "bridge"],
        related_standard="古建筑防工业振动技术规范（GB/T 50452-2008）",
    ),
    clause(
        "REF-S26-PLAN-CONST-ROAD-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.9.1 工程管理措施，OCR 行1464-1468",
        "长城附近施工前期修缮施工运输道路时，应尽量利用现有道路，不宜新修运输道路。",
        "施工运输道路",
        "施工活动邻近长城遗址或其保护范围的场景",
        ["施工期", "道路", "空间避让"],
        ["现有道路", "施工运输道路", "不应新修"],
        ["road", "bridge", "railway"],
    ),
    clause(
        "REF-S26-PLAN-CONST-STOCKPILE-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.9.1 工程管理措施，OCR 行1468",
        "长城附近施工时，材料堆放应远离长城。",
        "材料堆放距离",
        "施工材料堆放可能影响长城本体或保护范围的场景",
        ["施工期", "材料堆放", "空间避让"],
        ["材料堆放", "远离长城", "100m"],
        ["road", "bridge", "railway"],
        control_value="远离长城保证100m距离（参考报告做法）",
    ),
    clause(
        "REF-S26-PLAN-CONST-WASTE-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.9.1 工程管理措施，OCR 行1469-1471",
        "长城附近施工时，施工和生活垃圾应运至指定地点集中处理，严禁直接焚烧或随意倾倒。",
        "施工生活垃圾处理",
        "施工和生活垃圾可能污染长城周边环境的场景",
        ["施工期", "垃圾", "污染防治"],
        ["焚烧", "垃圾", "集中处理", "随意倾倒"],
        ["road", "bridge", "railway"],
    ),
    clause(
        "REF-S26-PLAN-CONST-BLAST-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.9.1 工程管理措施，OCR 行1468-1469",
        "长城附近桥梁施工时，应禁止放炮，以降低施工对文物本体及周边环境的影响。",
        "禁用爆破",
        "桥梁施工邻近长城遗址的场景",
        ["振动", "施工期", "爆破"],
        ["禁止放炮", "桥梁施工", "长城附近"],
        ["road", "bridge"],
    ),
    clause(
        "REF-S26-PLAN-OPER-NOISE-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.10.1 道路通行局部管控要求，OCR 行1481-1484",
        "道路运营期在跨越或邻近长城敏感点处，应设置禁鸣标志，以减少通行噪声。",
        "禁鸣标志",
        "道路运营噪声可能影响长城遗址或其环境的敏感点",
        ["噪声", "运营期", "交通管控"],
        ["禁鸣标志", "通行噪声", "敏感点"],
        ["road"],
    ),
    clause(
        "REF-S26-PLAN-OPER-SPEED-001",
        "REF_S26_PROTECTION_PLAN",
        SOURCES[0]["source_title"],
        "5.10.1 道路通行局部管控要求，OCR 行1485-1490",
        "道路运营期在途经长城遗址敏感区域时，可通过限速和设置减速带降低车辆高速通行造成的振动影响。",
        "限速与减速带",
        "道路运营振动可能影响长城遗址基础或周边结构物的敏感路段",
        ["振动", "运营期", "交通管控"],
        ["限速", "减速带", "车辆行驶", "长城遗址"],
        ["road"],
        control_value="参考报告建议敏感区域车辆限速60km/h",
    ),
    clause(
        "REF-S26-IA-BRIDGE-SPAN-001",
        "REF_S26_IMPACT_ASSESSMENT",
        SOURCES[1]["source_title"],
        "3.5.1 桥梁设计方案，OCR 行703-722",
        "公路桥梁跨越长城或新发现长城遗址时，应通过桥跨布置、桥墩位置和净空控制，从平面距离和高差上最大限度避让长城本体。",
        "桥跨布置避让",
        "公路桥梁跨越长城、冲沟或长城遗址邻近区域的方案比选场景",
        ["空间避让", "桥梁", "历史风貌"],
        ["桥梁跨越", "桥墩", "净空", "避让长城"],
        ["road", "bridge"],
        related_standard="公路桥涵设计通用规范（JTG D60-2015）",
    ),
    clause(
        "REF-S26-IA-GUARDRAIL-001",
        "REF_S26_IMPACT_ASSESSMENT",
        SOURCES[1]["source_title"],
        "3.5.1 桥梁护栏，OCR 行891-897",
        "公路桥梁邻近长城遗址时，桥梁护栏应按交通安全设施规范结合设计速度、桥梁线形、结构、高度和运行速度确定防护等级与形式。",
        "桥梁护栏防护等级",
        "桥梁邻近或跨越长城遗址且需控制桥面安全设施高度体量的场景",
        ["交通安全", "视觉景观", "桥梁"],
        ["桥梁护栏", "防护等级", "设计速度", "运行速度"],
        ["road", "bridge"],
        control_value="参考报告采用混凝土桥梁护栏，高度90cm",
        related_standard="公路桥梁安全设施设计规范（JTG D81-2017）",
    ),
    clause(
        "REF-S26-IA-LANDSCAPE-001",
        "REF_S26_IMPACT_ASSESSMENT",
        SOURCES[1]["source_title"],
        "5.4.3 相关减缓措施，OCR 行1792-1801",
        "桥梁工程影响文物周边景观时，桥梁装饰色调应与周围环境保持协调自然，造型应兼顾安全、实用和美观。",
        "桥梁色彩与造型",
        "桥梁工程对文物周边历史风貌、环境景观或视觉景观产生影响的场景",
        ["视觉景观", "历史风貌", "桥梁"],
        ["装饰色调", "协调自然", "造型", "景观"],
        ["road", "bridge"],
    ),
    clause(
        "REF-S26-IA-MUD-001",
        "REF_S26_IMPACT_ASSESSMENT",
        SOURCES[1]["source_title"],
        "5.4.3 相关减缓措施，OCR 行1792-1796",
        "桥梁施工或桩基施工应优先使用移动泥浆池，减少施工现场临时开挖工程，从而降低对文物周边环境的破坏。",
        "移动泥浆池",
        "桩基施工、桥梁施工产生泥浆和临时开挖的场景",
        ["施工期", "开挖", "环境扰动"],
        ["移动泥浆池", "临时开挖", "施工现场"],
        ["road", "bridge"],
    ),
    clause(
        "REF-S26-IA-VEGETATION-RESTORE-001",
        "REF_S26_IMPACT_ASSESSMENT",
        SOURCES[1]["source_title"],
        "5.4.3 相关减缓措施，OCR 行1797-1798",
        "施工破土区域应尽快恢复原有植被，以减少水土流失对长城基础的影响。",
        "施工破土区植被恢复",
        "施工破土、桥墩或桥梁工程影响长城基础和水土保持的场景",
        ["水土保持", "植被恢复"],
        ["恢复植被", "水土流失", "破土区域"],
        ["road", "bridge"],
    ),
    clause(
        "REF-S26-IA-LANDSCAPE-GREEN-001",
        "REF_S26_IMPACT_ASSESSMENT",
        SOURCES[1]["source_title"],
        "5.4.3 相关减缓措施，OCR 行1798-1799",
        "桥墩附近可种植耐旱耐贫瘠的乔木、灌木，通过绿化遮挡弱化工程外观色彩。",
        "绿化遮挡",
        "桥墩或桥梁工程外观色彩影响长城周边视觉景观的场景",
        ["视觉景观", "植被恢复"],
        ["绿化遮挡", "工程外观色彩", "乔木", "灌木"],
        ["road", "bridge"],
    ),
    clause(
        "REF-CHIFENG-VIB-LIMIT-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "四（二）运营期影响分析、五（一）评估依据，OCR 行849-955、1015-1017",
        "高铁或铁路运营振动可能影响全国重点文物保护单位长城本体时，可将文物本体容许振动速度控制限值设为0.1mm/s以内，并据此进行预测和监测。",
        "文物本体容许振动速度",
        "铁路、高铁或轨道交通下穿、邻近全国重点文物保护单位长城的振动评估场景",
        ["振动", "运营期", "限值"],
        ["容许振动速度", "0.1毫米/秒", "GB/T50452-2008", "高铁运营"],
        ["railway", "tunnel"],
        control_value="0.1mm/s以内（参考报告建议值）",
        related_standard="古建筑防工业振动技术规范（GB/T 50452-2008）",
    ),
    clause(
        "REF-CHIFENG-TUNNEL-NONBLAST-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "五（二）评估建议，OCR 行970-979、1019-1020",
        "铁路隧道下穿长城遗址时，宜采用非爆破法施工，以降低施工振动影响。",
        "非爆破施工",
        "铁路或高铁隧道下穿长城遗址且施工振动需要控制的场景",
        ["振动", "施工期", "减振"],
        ["非爆破法", "隧道", "施工振动"],
        ["railway", "tunnel"],
    ),
    clause(
        "REF-CHIFENG-TUNNEL-FLOATING-SLAB-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "五（二）评估建议，OCR 行970-979、1019-1020",
        "铁路隧道下穿长城遗址时，可设置钢弹簧浮置板减振道床，以降低运营振动影响。",
        "钢弹簧浮置板减振道床",
        "铁路或高铁隧道下穿长城遗址且运营振动需要控制的场景",
        ["振动", "运营期", "减振"],
        ["钢弹簧浮置板", "减振道床", "运营振动"],
        ["railway", "tunnel"],
    ),
    clause(
        "REF-CHIFENG-CONST-SITE-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）铁路工程建设防护措施，OCR 行1062-1065",
        "铁路或隧道施工场地、施工营地、固定作业场地应远离长城本体及其保护范围。",
        "施工场地布置",
        "铁路、隧道或线性工程施工场地邻近长城本体及保护范围的场景",
        ["施工期", "空间避让", "交通组织"],
        ["施工场地", "施工营地", "固定作业场地", "远离长城"],
        ["railway", "tunnel", "road"],
    ),
    clause(
        "REF-CHIFENG-CONST-VEHICLE-ROUTE-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）铁路工程建设防护措施，OCR 行1067-1069",
        "施工车辆特别是重型运输车辆的运行通路及施工便道应远离长城本体。",
        "施工车辆通路",
        "重型运输车辆或施工便道可能影响长城本体的施工组织场景",
        ["施工期", "空间避让", "交通组织"],
        ["重型运输车辆", "施工便道", "远离长城"],
        ["railway", "tunnel", "road"],
    ),
    clause(
        "REF-CHIFENG-CONST-BOUNDARY-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）铁路工程建设防护措施，OCR 行1071-1073",
        "隧道或线性工程施工应限定施工范围，严禁越界施工，避免破坏长城。",
        "施工边界控制",
        "施工场地或隧道工程位于长城建设控制地带、邻近保护范围的场景",
        ["施工期", "空间管控"],
        ["限定施工范围", "严禁越界施工", "长城"],
        ["railway", "tunnel", "road"],
    ),
    clause(
        "REF-CHIFENG-CHANCE-FIND-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）铁路工程建设防护措施，OCR 行1074-1079",
        "工程施工中发现历史遗存或出现影响文物本体安全的行为时，应立即停止施工、保护现场并报文物主管部门。",
        "施工发现文物处置",
        "建设工程施工中出现新发现文物或文物安全风险的场景",
        ["施工期", "考古前置", "应急处置"],
        ["发现历史遗存", "立即停止施工", "保护现场", "文物主管部门"],
        ["railway", "tunnel", "road", "building"],
        ["great_wall", "site", "tomb", "building"],
    ),
    clause(
        "REF-CHIFENG-LANDSCAPE-DESIGN-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）铁路工程建设防护措施，OCR 行1081-1087",
        "项目实施过程中应优化设计和施工方案，尽量减少在长城保护范围内的占地和土石方数量。",
        "占地与土石方控制",
        "线性工程或隧道工程施工影响长城保护范围的场景",
        ["历史风貌", "土石方", "施工期"],
        ["占地", "土石方", "优化设计", "施工方案"],
        ["railway", "tunnel", "road"],
    ),
    clause(
        "REF-CHIFENG-LANDSCAPE-RESTORE-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）铁路工程建设防护措施，OCR 行1089-1091、1022-1025",
        "隧道口或施工扰动区域完工后应及时覆土、整治土地，恢复原有历史风貌。",
        "完工后风貌恢复",
        "隧道口、施工场地或线性工程完工后需要恢复长城历史风貌的场景",
        ["历史风貌", "施工期", "恢复"],
        ["覆土", "土地整治", "恢复原有历史风貌"],
        ["railway", "tunnel", "road"],
    ),
    clause(
        "REF-CHIFENG-VIB-MONITOR-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）运营期保护措施，OCR 行1063-1072、1006-1014",
        "施工期及运营期应加强振动影响监测，发现长城本体技术指标异常时，应立即向运营单位和文物部门报告，并及时调整运营方案或采取保护措施。",
        "施工期和运营期振动监测",
        "铁路、高铁或轨道交通施工及运营振动可能影响长城本体的场景",
        ["振动", "监测", "施工期", "运营期"],
        ["振动监测", "异常情况", "调整运营方案", "文物部门"],
        ["railway", "tunnel"],
    ),
    clause(
        "REF-CHIFENG-BLAST-MONITOR-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）隧道施工振动控制，OCR 行1094-1104",
        "隧道爆破施工可能影响长城本体时，应对长城本体开展振动速度专项监测，并将振速控制在爆破安全规程及评估报告要求范围内。",
        "爆破振动监测与控制",
        "隧道或地下工程不可避免采用爆破法且邻近长城本体的场景",
        ["振动", "爆破", "监测", "施工期"],
        ["爆破施工", "振动速度专项监测", "爆破安全规程"],
        ["railway", "tunnel"],
        related_standard="爆破安全规程",
    ),
    clause(
        "REF-CHIFENG-BLAST-DELAY-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）隧道施工振动控制，OCR 行1106-1110",
        "隧道爆破施工应采用微差爆破减振技术，并合理选取段间隔时差。",
        "微差爆破减振",
        "隧道或地下工程不可避免采用爆破法且需控制文物振动影响的场景",
        ["振动", "爆破", "减振", "施工期"],
        ["微差爆破", "段间隔时差"],
        ["railway", "tunnel"],
    ),
    clause(
        "REF-CHIFENG-BLAST-CHARGE-001",
        "REF_CHIFENG_HSR_GREAT_WALL",
        SOURCES[2]["source_title"],
        "七（一）隧道施工振动控制，OCR 行1112-1118",
        "隧道爆破施工应将炸药量分散化、微量化，通过密布孔、浅打眼、少装药降低爆破振动影响。",
        "分散化微量化装药",
        "隧道或地下工程不可避免采用爆破法且需控制文物振动影响的场景",
        ["振动", "爆破", "减振", "施工期"],
        ["分散装药", "少装药", "密布孔", "浅打眼"],
        ["railway", "tunnel"],
    ),
    clause(
        "REF-AMO-ENV-AIR-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行123-128",
        "铁路工程涉及环境空气影响评价时，应明确采用的环境空气质量标准类别，并优先核对现行版本标准。",
        "环境空气质量标准类别",
        "铁路工程施工期或运营期涉及环境空气质量评价的场景",
        ["废气", "空气质量", "施工期", "运营期"],
        ["环境空气质量标准", "二级标准", "GB3095"],
        ["railway"],
        control_value="参考报告引用二级标准；需核对现行版本",
        related_standard="环境空气质量标准",
    ),
    clause(
        "REF-AMO-ENV-WATER-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行130-132",
        "铁路工程涉及地表水环境评价时，应明确采用的地表水环境质量类别，并优先核对现行版本标准。",
        "地表水环境质量类别",
        "铁路工程施工期或运营期涉及地表水环境评价的场景",
        ["地表水", "水环境", "废水"],
        ["地表水环境质量标准", "Ⅲ类标准", "GB3838"],
        ["railway"],
        control_value="参考报告引用Ⅲ类标准",
        related_standard="地表水环境质量标准",
    ),
    clause(
        "REF-AMO-ENV-NOISE-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行134-135",
        "铁路工程涉及声环境评价时，应根据敏感区和线路两侧环境功能明确采用的声环境质量标准类别。",
        "声环境质量类别",
        "铁路工程施工期或运营期涉及声环境敏感区、铁路两侧或居民文教区的场景",
        ["噪声", "声环境", "运营期"],
        ["声环境质量标准", "2类", "4b类", "GB3096"],
        ["railway"],
        control_value="参考报告引用2类、4b类标准",
        related_standard="声环境质量标准",
    ),
    clause(
        "REF-AMO-ENV-VIB-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行137-139、155-157",
        "铁路工程涉及环境振动评价时，应按居民文教区及铁路干线两侧等适用区域明确环境振动标准。",
        "环境振动标准类别",
        "铁路工程施工期或运营期涉及居民文教区、铁路干线两侧或文物敏感区振动评价的场景",
        ["振动", "运营期", "施工期"],
        ["城市区域环境振动标准", "居民文教区", "铁路干线两侧", "GB10070"],
        ["railway"],
        related_standard="城市区域环境振动标准",
    ),
    clause(
        "REF-AMO-ENV-WASTEWATER-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行145-147",
        "铁路工程涉及污水排放时，应明确采用的污水综合排放标准级别，并优先核对现行版本及受纳去向。",
        "污水排放标准级别",
        "铁路工程施工期或运营期产生污水、废水并需达标排放的场景",
        ["污水", "废水", "排放限值"],
        ["污水综合排放标准", "一级标准", "GB8978"],
        ["railway"],
        control_value="参考报告引用一级标准；需核对受纳水体/管网去向",
        related_standard="污水综合排放标准",
    ),
    clause(
        "REF-AMO-ENV-RAILWAY-BOUNDARY-NOISE-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行149-150",
        "铁路工程涉及运营期铁路边界噪声时，应对照铁路边界噪声限值及其测量方法。",
        "铁路边界噪声",
        "铁路工程运营边界噪声评价场景",
        ["噪声", "运营期"],
        ["铁路边界噪声", "GB12525"],
        ["railway"],
        related_standard="铁路边界噪声限值及其测量方法",
    ),
    clause(
        "REF-AMO-ENV-CONSTRUCTION-NOISE-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "（四）新建阿莫铁路工程施工标准，OCR 行152-153",
        "铁路工程涉及施工场界噪声时，应对照建筑施工噪声排放标准。",
        "建筑施工场界噪声",
        "铁路工程施工场界噪声评价场景",
        ["噪声", "施工期"],
        ["建筑施工场界环境噪声", "GB12523", "施工场界噪声"],
        ["railway"],
        related_standard="建筑施工噪声排放标准",
    ),
    clause(
        "REF-AMO-CONST-FLAG-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "施工期保护措施，OCR 行470-472",
        "施工前应对金界壕或长城遗址进行插旗标记，明确现场保护边界。",
        "遗址现场标记",
        "铁路或桥梁施工邻近金界壕、长城遗址等线性遗存的场景",
        ["施工期", "现场管控"],
        ["插旗标记", "金界壕", "保护边界"],
        ["railway", "bridge"],
    ),
    clause(
        "REF-AMO-CONST-TRAINING-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "施工期保护措施，OCR 行472-474",
        "施工前应对施工人员进行文物保护教育培训。",
        "施工人员教育培训",
        "铁路或桥梁施工邻近金界壕、长城遗址等线性遗存的场景",
        ["施工期", "培训"],
        ["教育培训", "施工人员", "文物保护"],
        ["railway", "bridge"],
    ),
    clause(
        "REF-AMO-CONST-NO-STOCKPILE-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "施工期保护措施，OCR 行472-476",
        "施工期间应禁止在金界壕或长城遗址上堆放杂物等可能损坏遗址的行为。",
        "遗址上禁止堆放杂物",
        "铁路或桥梁施工邻近金界壕、长城遗址等线性遗存的场景",
        ["施工期", "现场管控", "材料堆放"],
        ["堆放杂物", "金界壕", "损坏遗址"],
        ["railway", "bridge"],
    ),
    clause(
        "REF-AMO-CONST-EXCAVATION-001",
        "REF_AMO_RAILWAY",
        SOURCES[3]["source_title"],
        "施工期保护措施，OCR 行478-482",
        "桥墩基础施工可采用钢板桩围堰和垂直开挖，以减少开挖土方、缩小施工范围，并使施工作业面尽可能远离文物本体。",
        "桥墩基础开挖控制",
        "铁路桥梁桥墩基础施工邻近文物本体或保护范围的场景",
        ["施工期", "开挖", "空间避让"],
        ["钢板桩围堰", "垂直开挖", "缩小施工范围", "远离文物本体"],
        ["railway", "bridge"],
    ),
]


def main() -> None:
    write_jsonl(SOURCE_OUT, SOURCES)
    write_jsonl(CLAUSE_OUT, CLAUSES)
    manifest = {
        "generated_at": now_iso(),
        "source_count": len(SOURCES),
        "clause_count": len(CLAUSES),
        "source_file": str(SOURCE_OUT),
        "clause_file": str(CLAUSE_OUT),
    }
    MANIFEST_OUT.write_text(json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
